name: "expense-tracking-migration"
services:
  db-old:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: expenses_db      
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - expenses-db-postgres-volume:/var/lib/postgresql/data
    command: postgres -c 'max_connections=100'
  
  db-new:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: expenses_db      
    ports:
      - "5434:5432"  # Different port for new database
    volumes:
      - expenses-db-postgres-volume-new:/var/lib/postgresql/data
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
    command: postgres -c 'max_connections=100'

volumes:
  expenses-db-postgres-volume:
    driver: local
  expenses-db-postgres-volume-new:
    driver: local 