name: "expense-tracking"
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: expenses_db      
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d expenses_db -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - expenses-db-postgres-volume:/var/lib/postgresql/data
      - ./scripts/sql/:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/expenses_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
volumes:
  expenses-db-postgres-volume:
    driver: local
